# Generated by Django 4.2.7 on 2026-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentteachermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
