# Generated by Django 4.2.7 on 2026-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_tenant_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
