# Generated by Django 4.2.7 on 2026-03-11 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def convert_teacher_profile_to_user(apps, schema_editor):
    """Map old TeacherProfile FK values to their User IDs."""
    Examination = apps.get_model('examination', 'Examination')
    TeacherProfile = apps.get_model('accounts', 'TeacherProfile')
    for exam in Examination.objects.all():
        if exam.created_by_id:
            try:
                tp = TeacherProfile.objects.get(pk=exam.created_by_id)
                exam.created_by_id = tp.user_id
                exam.save(update_fields=['created_by_id'])
            except TeacherProfile.DoesNotExist:
                exam.created_by_id = None
                exam.save(update_fields=['created_by_id'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_parentteachermessage'),
        ('examination', '0001_initial'),
    ]

    operations = [
        # Step 1: Make nullable first (still pointing to TeacherProfile)
        migrations.AlterField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='accounts.TeacherProfile',
            ),
        ),
        # Step 2: Convert TeacherProfile IDs → User IDs
        migrations.RunPython(convert_teacher_profile_to_user, migrations.RunPython.noop),
        # Step 3: Point FK to User model
        migrations.AlterField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_examinations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
