# Generated by Django 4.2.7 on 2026-03-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentteachermessage'),
        ('examination', '0002_alter_examination_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='has_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='internal_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='external_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='InternalComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField()),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_components', to='examination.examination')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examination.internalcomponent')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('component', 'student')},
            },
        ),
    ]
