# Generated by Django 4.2.7 on 2026-03-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('examination', '0005_resultpublication_by_examtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('tenant', 'name')},
        ),
    ]
